using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Windows.Forms;

namespace Bai2_PhieuSuCoIT
{
    partial class Form1
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            grpThongTin = new GroupBox();
            lblMaPhieu = new Label();
            txtMaPhieu = new TextBox();
            lblNguoiYeuCau = new Label();
            txtNguoiYeuCau = new TextBox();
            lblNgay = new Label();
            dtpNgayGhiNhan = new DateTimePicker();
            grpUuTien = new GroupBox();
            rdoThap = new RadioButton();
            rdoTrungBinh = new RadioButton();
            rdoKhanCap = new RadioButton();
            grpPhanLoai = new GroupBox();
            lblLoaiSuCo = new Label();
            cboLoaiSuCo = new ComboBox();
            grpThietBi = new GroupBox();
            chkMayTinhBan = new CheckBox();
            chkLaptop = new CheckBox();
            chkMayIn = new CheckBox();
            chkDienThoai = new CheckBox();
            lblMoTa = new Label();
            txtMoTa = new TextBox();
            grpAnhLoi = new GroupBox();
            picAnhLoi = new PictureBox();
            btnTaiAnh = new Button();
            btnGui = new Button();
            btnNhapLai = new Button();
            grpThongTin.SuspendLayout();
            grpUuTien.SuspendLayout();
            grpPhanLoai.SuspendLayout();
            grpThietBi.SuspendLayout();
            grpAnhLoi.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)picAnhLoi).BeginInit();
            SuspendLayout();
            grpThongTin.Controls.Add(lblMaPhieu);
            grpThongTin.Controls.Add(txtMaPhieu);
            grpThongTin.Controls.Add(lblNguoiYeuCau);
            grpThongTin.Controls.Add(txtNguoiYeuCau);
            grpThongTin.Controls.Add(lblNgay);
            grpThongTin.Controls.Add(dtpNgayGhiNhan);
            grpThongTin.Controls.Add(grpUuTien);
            grpThongTin.Location = new Point(15, 12);
            grpThongTin.Name = "grpThongTin";
            grpThongTin.Size = new Size(400, 225);
            grpThongTin.TabIndex = 0;
            grpThongTin.TabStop = false;
            grpThongTin.Text = "Thông tin phiếu";
            lblMaPhieu.AutoSize = true;
            lblMaPhieu.Location = new Point(15, 33);
            lblMaPhieu.Name = "lblMaPhieu";
            lblMaPhieu.Size = new Size(70, 20);
            lblMaPhieu.Text = "Mã phiếu:";
            txtMaPhieu.Location = new Point(140, 30);
            txtMaPhieu.Name = "txtMaPhieu";
            txtMaPhieu.Size = new Size(240, 27);
            txtMaPhieu.TabIndex = 0;
            lblNguoiYeuCau.AutoSize = true;
            lblNguoiYeuCau.Location = new Point(15, 68);
            lblNguoiYeuCau.Name = "lblNguoiYeuCau";
            lblNguoiYeuCau.Size = new Size(100, 20);
            lblNguoiYeuCau.Text = "Người yêu cầu:";
            txtNguoiYeuCau.Location = new Point(140, 65);
            txtNguoiYeuCau.Name = "txtNguoiYeuCau";
            txtNguoiYeuCau.Size = new Size(240, 27);
            txtNguoiYeuCau.TabIndex = 1;
            lblNgay.AutoSize = true;
            lblNgay.Location = new Point(15, 103);
            lblNgay.Name = "lblNgay";
            lblNgay.Size = new Size(110, 20);
            lblNgay.Text = "Ngày ghi nhận:";
            dtpNgayGhiNhan.CustomFormat = "dd/MM/yyyy HH:mm";
            dtpNgayGhiNhan.Format = DateTimePickerFormat.Custom;
            dtpNgayGhiNhan.Location = new Point(140, 100);
            dtpNgayGhiNhan.Name = "dtpNgayGhiNhan";
            dtpNgayGhiNhan.Size = new Size(240, 27);
            dtpNgayGhiNhan.TabIndex = 2;
            grpUuTien.Controls.Add(rdoThap);
            grpUuTien.Controls.Add(rdoTrungBinh);
            grpUuTien.Controls.Add(rdoKhanCap);
            grpUuTien.Location = new Point(15, 140);
            grpUuTien.Name = "grpUuTien";
            grpUuTien.Size = new Size(365, 65);
            grpUuTien.TabIndex = 3;
            grpUuTien.TabStop = false;
            grpUuTien.Text = "Mức độ ưu tiên";
            rdoThap.AutoSize = true;
            rdoThap.Location = new Point(15, 28);
            rdoThap.Name = "rdoThap";
            rdoThap.Size = new Size(64, 24);
            rdoThap.TabIndex = 0;
            rdoThap.Text = "Thấp";
            rdoTrungBinh.AutoSize = true;
            rdoTrungBinh.Checked = true;
            rdoTrungBinh.Location = new Point(115, 28);
            rdoTrungBinh.Name = "rdoTrungBinh";
            rdoTrungBinh.Size = new Size(104, 24);
            rdoTrungBinh.TabIndex = 1;
            rdoTrungBinh.TabStop = true;
            rdoTrungBinh.Text = "Trung bình";
            rdoKhanCap.AutoSize = true;
            rdoKhanCap.ForeColor = Color.Firebrick;
            rdoKhanCap.Location = new Point(245, 28);
            rdoKhanCap.Name = "rdoKhanCap";
            rdoKhanCap.Size = new Size(95, 24);
            rdoKhanCap.TabIndex = 2;
            rdoKhanCap.Text = "Khẩn cấp";
            grpPhanLoai.Controls.Add(lblLoaiSuCo);
            grpPhanLoai.Controls.Add(cboLoaiSuCo);
            grpPhanLoai.Controls.Add(grpThietBi);
            grpPhanLoai.Controls.Add(lblMoTa);
            grpPhanLoai.Controls.Add(txtMoTa);
            grpPhanLoai.Location = new Point(15, 245);
            grpPhanLoai.Name = "grpPhanLoai";
            grpPhanLoai.Size = new Size(400, 265);
            grpPhanLoai.TabIndex = 1;
            grpPhanLoai.TabStop = false;
            grpPhanLoai.Text = "Phân loại & Chi tiết";
            lblLoaiSuCo.AutoSize = true;
            lblLoaiSuCo.Location = new Point(15, 33);
            lblLoaiSuCo.Name = "lblLoaiSuCo";
            lblLoaiSuCo.Size = new Size(80, 20);
            lblLoaiSuCo.Text = "Loại sự cố:";
            cboLoaiSuCo.DropDownStyle = ComboBoxStyle.DropDownList;
            cboLoaiSuCo.Items.AddRange(new object[] { "Phần cứng", "Phần mềm", "Mạng", "Tài khoản" });
            cboLoaiSuCo.Location = new Point(140, 30);
            cboLoaiSuCo.Name = "cboLoaiSuCo";
            cboLoaiSuCo.Size = new Size(240, 28);
            cboLoaiSuCo.TabIndex = 0;
            grpThietBi.Controls.Add(chkMayTinhBan);
            grpThietBi.Controls.Add(chkLaptop);
            grpThietBi.Controls.Add(chkMayIn);
            grpThietBi.Controls.Add(chkDienThoai);
            grpThietBi.Location = new Point(15, 68);
            grpThietBi.Name = "grpThietBi";
            grpThietBi.Size = new Size(365, 90);
            grpThietBi.TabIndex = 1;
            grpThietBi.TabStop = false;
            grpThietBi.Text = "Thiết bị ảnh hưởng";
            chkMayTinhBan.AutoSize = true;
            chkMayTinhBan.Location = new Point(15, 27);
            chkMayTinhBan.Name = "chkMayTinhBan";
            chkMayTinhBan.Size = new Size(125, 24);
            chkMayTinhBan.TabIndex = 0;
            chkMayTinhBan.Text = "Máy tính bàn";
            chkLaptop.AutoSize = true;
            chkLaptop.Location = new Point(190, 27);
            chkLaptop.Name = "chkLaptop";
            chkLaptop.Size = new Size(77, 24);
            chkLaptop.TabIndex = 1;
            chkLaptop.Text = "Laptop";
            chkMayIn.AutoSize = true;
            chkMayIn.Location = new Point(15, 57);
            chkMayIn.Name = "chkMayIn";
            chkMayIn.Size = new Size(76, 24);
            chkMayIn.TabIndex = 2;
            chkMayIn.Text = "Máy in";
            chkDienThoai.AutoSize = true;
            chkDienThoai.Location = new Point(190, 57);
            chkDienThoai.Name = "chkDienThoai";
            chkDienThoai.Size = new Size(100, 24);
            chkDienThoai.TabIndex = 3;
            chkDienThoai.Text = "Điện thoại";
            lblMoTa.AutoSize = true;
            lblMoTa.Location = new Point(15, 168);
            lblMoTa.Name = "lblMoTa";
            lblMoTa.Size = new Size(100, 20);
            lblMoTa.Text = "Mô tả sự cố:";
            txtMoTa.Location = new Point(15, 192);
            txtMoTa.Multiline = true;
            txtMoTa.Name = "txtMoTa";
            txtMoTa.ScrollBars = ScrollBars.Vertical;
            txtMoTa.Size = new Size(365, 60);
            txtMoTa.TabIndex = 2;
            grpAnhLoi.Controls.Add(picAnhLoi);
            grpAnhLoi.Controls.Add(btnTaiAnh);
            grpAnhLoi.Location = new Point(430, 12);
            grpAnhLoi.Name = "grpAnhLoi";
            grpAnhLoi.Size = new Size(340, 498);
            grpAnhLoi.TabIndex = 2;
            grpAnhLoi.TabStop = false;
            grpAnhLoi.Text = "Ảnh chụp lỗi";
            picAnhLoi.BackColor = Color.WhiteSmoke;
            picAnhLoi.BorderStyle = BorderStyle.FixedSingle;
            picAnhLoi.Location = new Point(15, 30);
            picAnhLoi.Name = "picAnhLoi";
            picAnhLoi.Size = new Size(310, 405);
            picAnhLoi.SizeMode = PictureBoxSizeMode.StretchImage;
            picAnhLoi.TabStop = false;
            btnTaiAnh.Location = new Point(15, 445);
            btnTaiAnh.Name = "btnTaiAnh";
            btnTaiAnh.Size = new Size(310, 38);
            btnTaiAnh.TabIndex = 0;
            btnTaiAnh.Text = "Tải ảnh lỗi...";
            btnTaiAnh.UseVisualStyleBackColor = true;
            btnTaiAnh.Click += btnTaiAnh_Click;
            btnGui.BackColor = Color.FromArgb(0, 120, 215);
            btnGui.FlatStyle = FlatStyle.Flat;
            btnGui.ForeColor = Color.White;
            btnGui.Location = new Point(530, 525);
            btnGui.Name = "btnGui";
            btnGui.Size = new Size(120, 40);
            btnGui.TabIndex = 3;
            btnGui.Text = "&Gửi yêu cầu";
            btnGui.UseVisualStyleBackColor = false;
            btnGui.Click += btnGui_Click;
            btnNhapLai.Location = new Point(660, 525);
            btnNhapLai.Name = "btnNhapLai";
            btnNhapLai.Size = new Size(110, 40);
            btnNhapLai.TabIndex = 4;
            btnNhapLai.Text = "&Nhập lại";
            btnNhapLai.UseVisualStyleBackColor = true;
            btnNhapLai.Click += btnNhapLai_Click;
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(786, 580);
            Controls.Add(grpThongTin);
            Controls.Add(grpPhanLoai);
            Controls.Add(grpAnhLoi);
            Controls.Add(btnGui);
            Controls.Add(btnNhapLai);
            Font = new Font("Segoe UI", 9F);
            FormBorderStyle = FormBorderStyle.FixedSingle;
            MaximizeBox = false;
            Name = "Form1";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Bài 2 - Tiếp nhận & Phân loại sự cố IT";
            Load += Form1_Load;
            grpThongTin.ResumeLayout(false);
            grpThongTin.PerformLayout();
            grpUuTien.ResumeLayout(false);
            grpUuTien.PerformLayout();
            grpPhanLoai.ResumeLayout(false);
            grpPhanLoai.PerformLayout();
            grpThietBi.ResumeLayout(false);
            grpThietBi.PerformLayout();
            grpAnhLoi.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)picAnhLoi).EndInit();
            ResumeLayout(false);
        }

        #endregion

        private GroupBox grpThongTin;
        private Label lblMaPhieu;
        private TextBox txtMaPhieu;
        private Label lblNguoiYeuCau;
        private TextBox txtNguoiYeuCau;
        private Label lblNgay;
        private DateTimePicker dtpNgayGhiNhan;
        private GroupBox grpUuTien;
        private RadioButton rdoThap;
        private RadioButton rdoTrungBinh;
        private RadioButton rdoKhanCap;
        private GroupBox grpPhanLoai;
        private Label lblLoaiSuCo;
        private ComboBox cboLoaiSuCo;
        private GroupBox grpThietBi;
        private CheckBox chkMayTinhBan;
        private CheckBox chkLaptop;
        private CheckBox chkMayIn;
        private CheckBox chkDienThoai;
        private Label lblMoTa;
        private TextBox txtMoTa;
        private GroupBox grpAnhLoi;
        private PictureBox picAnhLoi;
        private Button btnTaiAnh;
        private Button btnGui;
        private Button btnNhapLai;
    }
}
