using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Windows.Forms;

namespace Bai5_QuanLyDonGiaoHang
{
    partial class Form1
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            splitMain = new SplitContainer();
            tabThongTin = new TabControl();
            tabKhachHang = new TabPage();
            lblTenKH = new Label();
            txtTenKH = new TextBox();
            lblSDT = new Label();
            txtSDT = new TextBox();
            lblDiaChi = new Label();
            txtDiaChi = new TextBox();
            tabVanChuyen = new TabPage();
            lblLoaiVC = new Label();
            cboLoaiVC = new ComboBox();
            lblNgayGiao = new Label();
            dtpNgayGiao = new DateTimePicker();
            lblGhiChu = new Label();
            txtGhiChu = new TextBox();
            grpThemNhanh = new GroupBox();
            lblTenHang = new Label();
            txtTenHang = new TextBox();
            lblSoLuong = new Label();
            txtSoLuong = new TextBox();
            lblTrongLuong = new Label();
            txtTrongLuong = new TextBox();
            lblDonGia = new Label();
            txtDonGia = new TextBox();
            btnThemHang = new Button();
            btnLuuDon = new Button();
            btnDonMoi = new Button();
            dgvHangHoa = new DataGridView();
            colTenHang = new DataGridViewTextBoxColumn();
            colSoLuong = new DataGridViewTextBoxColumn();
            colTrongLuong = new DataGridViewTextBoxColumn();
            colDonGia = new DataGridViewTextBoxColumn();
            colThanhTien = new DataGridViewTextBoxColumn();
            lblHuongDan = new Label();
            statusStrip = new StatusStrip();
            lblThoiGian = new ToolStripStatusLabel();
            lblSpring = new ToolStripStatusLabel();
            lblTongSL = new ToolStripStatusLabel();
            lblTongKL = new ToolStripStatusLabel();
            lblTongTien = new ToolStripStatusLabel();
            timerDongHo = new System.Windows.Forms.Timer(components);
            errorProvider = new ErrorProvider(components);
            ((System.ComponentModel.ISupportInitialize)splitMain).BeginInit();
            splitMain.Panel1.SuspendLayout();
            splitMain.Panel2.SuspendLayout();
            splitMain.SuspendLayout();
            tabThongTin.SuspendLayout();
            tabKhachHang.SuspendLayout();
            tabVanChuyen.SuspendLayout();
            grpThemNhanh.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvHangHoa).BeginInit();
            statusStrip.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)errorProvider).BeginInit();
            SuspendLayout();
            splitMain.Dock = DockStyle.Fill;
            splitMain.FixedPanel = FixedPanel.Panel1;
            splitMain.Location = new Point(0, 0);
            splitMain.Name = "splitMain";
            splitMain.Panel1.Controls.Add(tabThongTin);
            splitMain.Panel1.Controls.Add(grpThemNhanh);
            splitMain.Panel1.Controls.Add(btnLuuDon);
            splitMain.Panel1.Controls.Add(btnDonMoi);
            splitMain.Panel1.Padding = new Padding(8);
            splitMain.Panel2.Controls.Add(dgvHangHoa);
            splitMain.Panel2.Controls.Add(lblHuongDan);
            splitMain.Panel2.Padding = new Padding(8);
            splitMain.Size = new Size(1100, 594);
            splitMain.SplitterDistance = 380;
            splitMain.SplitterWidth = 6;
            splitMain.TabIndex = 0;
            tabThongTin.Controls.Add(tabKhachHang);
            tabThongTin.Controls.Add(tabVanChuyen);
            tabThongTin.Location = new Point(10, 10);
            tabThongTin.Name = "tabThongTin";
            tabThongTin.SelectedIndex = 0;
            tabThongTin.Size = new Size(360, 235);
            tabThongTin.TabIndex = 0;
            tabKhachHang.Controls.Add(lblTenKH);
            tabKhachHang.Controls.Add(txtTenKH);
            tabKhachHang.Controls.Add(lblSDT);
            tabKhachHang.Controls.Add(txtSDT);
            tabKhachHang.Controls.Add(lblDiaChi);
            tabKhachHang.Controls.Add(txtDiaChi);
            tabKhachHang.Location = new Point(4, 29);
            tabKhachHang.Name = "tabKhachHang";
            tabKhachHang.Padding = new Padding(3);
            tabKhachHang.Size = new Size(352, 202);
            tabKhachHang.TabIndex = 0;
            tabKhachHang.Text = "Khách hàng";
            tabKhachHang.UseVisualStyleBackColor = true;
            lblTenKH.AutoSize = true;
            lblTenKH.Location = new Point(10, 18);
            lblTenKH.Name = "lblTenKH";
            lblTenKH.Size = new Size(100, 20);
            lblTenKH.Text = "Tên khách:";
            txtTenKH.Location = new Point(110, 15);
            txtTenKH.Name = "txtTenKH";
            txtTenKH.Size = new Size(215, 27);
            txtTenKH.TabIndex = 0;
            lblSDT.AutoSize = true;
            lblSDT.Location = new Point(10, 55);
            lblSDT.Name = "lblSDT";
            lblSDT.Size = new Size(100, 20);
            lblSDT.Text = "Điện thoại:";
            txtSDT.Location = new Point(110, 52);
            txtSDT.MaxLength = 11;
            txtSDT.Name = "txtSDT";
            txtSDT.Size = new Size(215, 27);
            txtSDT.TabIndex = 1;
            lblDiaChi.AutoSize = true;
            lblDiaChi.Location = new Point(10, 92);
            lblDiaChi.Name = "lblDiaChi";
            lblDiaChi.Size = new Size(100, 20);
            lblDiaChi.Text = "Địa chỉ giao:";
            txtDiaChi.Location = new Point(110, 89);
            txtDiaChi.Multiline = true;
            txtDiaChi.Name = "txtDiaChi";
            txtDiaChi.Size = new Size(215, 90);
            txtDiaChi.TabIndex = 2;
            tabVanChuyen.Controls.Add(lblLoaiVC);
            tabVanChuyen.Controls.Add(cboLoaiVC);
            tabVanChuyen.Controls.Add(lblNgayGiao);
            tabVanChuyen.Controls.Add(dtpNgayGiao);
            tabVanChuyen.Controls.Add(lblGhiChu);
            tabVanChuyen.Controls.Add(txtGhiChu);
            tabVanChuyen.Location = new Point(4, 29);
            tabVanChuyen.Name = "tabVanChuyen";
            tabVanChuyen.Padding = new Padding(3);
            tabVanChuyen.Size = new Size(352, 202);
            tabVanChuyen.TabIndex = 1;
            tabVanChuyen.Text = "Vận chuyển";
            tabVanChuyen.UseVisualStyleBackColor = true;
            lblLoaiVC.AutoSize = true;
            lblLoaiVC.Location = new Point(10, 18);
            lblLoaiVC.Name = "lblLoaiVC";
            lblLoaiVC.Size = new Size(100, 20);
            lblLoaiVC.Text = "Loại vận chuyển:";
            cboLoaiVC.DropDownStyle = ComboBoxStyle.DropDownList;
            cboLoaiVC.Items.AddRange(new object[] { "Tiêu chuẩn (3-5 ngày)", "Nhanh (1-2 ngày)", "Hỏa tốc (trong ngày)" });
            cboLoaiVC.Location = new Point(130, 15);
            cboLoaiVC.Name = "cboLoaiVC";
            cboLoaiVC.Size = new Size(195, 28);
            cboLoaiVC.TabIndex = 0;
            lblNgayGiao.AutoSize = true;
            lblNgayGiao.Location = new Point(10, 55);
            lblNgayGiao.Name = "lblNgayGiao";
            lblNgayGiao.Size = new Size(100, 20);
            lblNgayGiao.Text = "Ngày giao dự kiến:";
            dtpNgayGiao.CustomFormat = "dd/MM/yyyy";
            dtpNgayGiao.Format = DateTimePickerFormat.Custom;
            dtpNgayGiao.Location = new Point(130, 52);
            dtpNgayGiao.Name = "dtpNgayGiao";
            dtpNgayGiao.Size = new Size(195, 27);
            dtpNgayGiao.TabIndex = 1;
            lblGhiChu.AutoSize = true;
            lblGhiChu.Location = new Point(10, 92);
            lblGhiChu.Name = "lblGhiChu";
            lblGhiChu.Size = new Size(100, 20);
            lblGhiChu.Text = "Ghi chú:";
            txtGhiChu.Location = new Point(130, 89);
            txtGhiChu.Multiline = true;
            txtGhiChu.Name = "txtGhiChu";
            txtGhiChu.Size = new Size(195, 90);
            txtGhiChu.TabIndex = 2;
            grpThemNhanh.Controls.Add(lblTenHang);
            grpThemNhanh.Controls.Add(txtTenHang);
            grpThemNhanh.Controls.Add(lblSoLuong);
            grpThemNhanh.Controls.Add(txtSoLuong);
            grpThemNhanh.Controls.Add(lblTrongLuong);
            grpThemNhanh.Controls.Add(txtTrongLuong);
            grpThemNhanh.Controls.Add(lblDonGia);
            grpThemNhanh.Controls.Add(txtDonGia);
            grpThemNhanh.Controls.Add(btnThemHang);
            grpThemNhanh.Location = new Point(10, 255);
            grpThemNhanh.Name = "grpThemNhanh";
            grpThemNhanh.Size = new Size(360, 235);
            grpThemNhanh.TabIndex = 1;
            grpThemNhanh.TabStop = false;
            grpThemNhanh.Text = "Thêm nhanh hàng hóa";
            lblTenHang.AutoSize = true;
            lblTenHang.Location = new Point(14, 33);
            lblTenHang.Name = "lblTenHang";
            lblTenHang.Size = new Size(75, 20);
            lblTenHang.Text = "Tên hàng:";
            txtTenHang.Location = new Point(130, 30);
            txtTenHang.Name = "txtTenHang";
            txtTenHang.Size = new Size(195, 27);
            txtTenHang.TabIndex = 0;
            lblSoLuong.AutoSize = true;
            lblSoLuong.Location = new Point(14, 70);
            lblSoLuong.Name = "lblSoLuong";
            lblSoLuong.Size = new Size(70, 20);
            lblSoLuong.Text = "Số lượng:";
            txtSoLuong.Location = new Point(130, 67);
            txtSoLuong.Name = "txtSoLuong";
            txtSoLuong.Size = new Size(195, 27);
            txtSoLuong.TabIndex = 1;
            txtSoLuong.TextAlign = HorizontalAlignment.Right;
            txtSoLuong.TextChanged += txtSoLuong_TextChanged;
            lblTrongLuong.AutoSize = true;
            lblTrongLuong.Location = new Point(14, 107);
            lblTrongLuong.Name = "lblTrongLuong";
            lblTrongLuong.Size = new Size(115, 20);
            lblTrongLuong.Text = "Trọng lượng (kg):";
            txtTrongLuong.Location = new Point(130, 104);
            txtTrongLuong.Name = "txtTrongLuong";
            txtTrongLuong.Size = new Size(195, 27);
            txtTrongLuong.TabIndex = 2;
            txtTrongLuong.TextAlign = HorizontalAlignment.Right;
            txtTrongLuong.TextChanged += txtTrongLuong_TextChanged;
            lblDonGia.AutoSize = true;
            lblDonGia.Location = new Point(14, 144);
            lblDonGia.Name = "lblDonGia";
            lblDonGia.Size = new Size(65, 20);
            lblDonGia.Text = "Đơn giá:";
            txtDonGia.Location = new Point(130, 141);
            txtDonGia.Name = "txtDonGia";
            txtDonGia.Size = new Size(195, 27);
            txtDonGia.TabIndex = 3;
            txtDonGia.TextAlign = HorizontalAlignment.Right;
            txtDonGia.TextChanged += txtDonGia_TextChanged;
            btnThemHang.Location = new Point(130, 182);
            btnThemHang.Name = "btnThemHang";
            btnThemHang.Size = new Size(195, 36);
            btnThemHang.TabIndex = 4;
            btnThemHang.Text = "Thêm vào đơn ➜";
            btnThemHang.UseVisualStyleBackColor = true;
            btnThemHang.Click += btnThemHang_Click;
            btnLuuDon.BackColor = Color.FromArgb(0, 120, 215);
            btnLuuDon.FlatStyle = FlatStyle.Flat;
            btnLuuDon.ForeColor = Color.White;
            btnLuuDon.Location = new Point(10, 505);
            btnLuuDon.Name = "btnLuuDon";
            btnLuuDon.Size = new Size(175, 42);
            btnLuuDon.TabIndex = 2;
            btnLuuDon.Text = "Lưu đơn hàng";
            btnLuuDon.UseVisualStyleBackColor = false;
            btnLuuDon.Click += btnLuuDon_Click;
            btnDonMoi.Location = new Point(195, 505);
            btnDonMoi.Name = "btnDonMoi";
            btnDonMoi.Size = new Size(175, 42);
            btnDonMoi.TabIndex = 3;
            btnDonMoi.Text = "Tạo đơn mới";
            btnDonMoi.UseVisualStyleBackColor = true;
            btnDonMoi.Click += btnDonMoi_Click;
            lblHuongDan.BackColor = Color.FromArgb(232, 241, 251);
            lblHuongDan.Dock = DockStyle.Top;
            lblHuongDan.Location = new Point(8, 8);
            lblHuongDan.Name = "lblHuongDan";
            lblHuongDan.Padding = new Padding(6, 0, 0, 0);
            lblHuongDan.Size = new Size(698, 32);
            lblHuongDan.Text = "CHI TIẾT HÀNG HÓA    |    F2: thêm dòng mới    •    Delete: xóa dòng đang chọn";
            lblHuongDan.TextAlign = ContentAlignment.MiddleLeft;
            dgvHangHoa.AllowUserToAddRows = false;
            dgvHangHoa.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvHangHoa.BackgroundColor = Color.White;
            dgvHangHoa.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dgvHangHoa.Columns.AddRange(new DataGridViewColumn[] { colTenHang, colSoLuong, colTrongLuong, colDonGia, colThanhTien });
            dgvHangHoa.Dock = DockStyle.Fill;
            dgvHangHoa.EditMode = DataGridViewEditMode.EditOnKeystroke;
            dgvHangHoa.Location = new Point(8, 40);
            dgvHangHoa.MultiSelect = false;
            dgvHangHoa.Name = "dgvHangHoa";
            dgvHangHoa.RowHeadersWidth = 40;
            dgvHangHoa.Size = new Size(698, 546);
            dgvHangHoa.TabIndex = 0;
            dgvHangHoa.CellValidating += dgvHangHoa_CellValidating;
            dgvHangHoa.CellValueChanged += dgvHangHoa_CellValueChanged;
            dgvHangHoa.DataError += dgvHangHoa_DataError;
            dgvHangHoa.RowsAdded += dgvHangHoa_RowsAdded;
            dgvHangHoa.RowsRemoved += dgvHangHoa_RowsRemoved;
            colTenHang.FillWeight = 35F;
            colTenHang.HeaderText = "Tên hàng";
            colTenHang.Name = "colTenHang";
            colSoLuong.FillWeight = 13F;
            colSoLuong.HeaderText = "Số lượng";
            colSoLuong.Name = "colSoLuong";
            colTrongLuong.FillWeight = 16F;
            colTrongLuong.HeaderText = "Trọng lượng (kg)";
            colTrongLuong.Name = "colTrongLuong";
            colDonGia.FillWeight = 17F;
            colDonGia.HeaderText = "Đơn giá";
            colDonGia.Name = "colDonGia";
            colThanhTien.FillWeight = 19F;
            colThanhTien.HeaderText = "Thành tiền";
            colThanhTien.Name = "colThanhTien";
            colThanhTien.ReadOnly = true;
            statusStrip.ImageScalingSize = new Size(20, 20);
            statusStrip.Items.AddRange(new ToolStripItem[] { lblThoiGian, lblSpring, lblTongSL, lblTongKL, lblTongTien });
            statusStrip.Location = new Point(0, 594);
            statusStrip.Name = "statusStrip";
            statusStrip.Size = new Size(1100, 30);
            statusStrip.TabIndex = 1;
            lblThoiGian.Name = "lblThoiGian";
            lblThoiGian.Size = new Size(150, 24);
            lblThoiGian.Text = "00:00:00";
            lblSpring.Name = "lblSpring";
            lblSpring.Size = new Size(500, 24);
            lblSpring.Spring = true;
            lblTongSL.BorderSides = ToolStripStatusLabelBorderSides.Left;
            lblTongSL.Name = "lblTongSL";
            lblTongSL.Size = new Size(110, 24);
            lblTongSL.Text = "Tổng SL: 0";
            lblTongKL.BorderSides = ToolStripStatusLabelBorderSides.Left;
            lblTongKL.Name = "lblTongKL";
            lblTongKL.Size = new Size(130, 24);
            lblTongKL.Text = "Tổng KL: 0 kg";
            lblTongTien.BorderSides = ToolStripStatusLabelBorderSides.Left;
            lblTongTien.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            lblTongTien.ForeColor = Color.Firebrick;
            lblTongTien.Name = "lblTongTien";
            lblTongTien.Size = new Size(150, 24);
            lblTongTien.Text = "Tổng tiền: 0 đ";
            timerDongHo.Interval = 1000;
            timerDongHo.Tick += timerDongHo_Tick;
            errorProvider.BlinkStyle = ErrorBlinkStyle.NeverBlink;
            errorProvider.ContainerControl = this;
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1100, 624);
            Controls.Add(splitMain);
            Controls.Add(statusStrip);
            Font = new Font("Segoe UI", 9F);
            MinimumSize = new Size(1000, 670);
            Name = "Form1";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Bài 5 - Bảng điều khiển Quản lý Đơn giao hàng";
            Load += Form1_Load;
            splitMain.Panel1.ResumeLayout(false);
            splitMain.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)splitMain).EndInit();
            splitMain.ResumeLayout(false);
            tabThongTin.ResumeLayout(false);
            tabKhachHang.ResumeLayout(false);
            tabKhachHang.PerformLayout();
            tabVanChuyen.ResumeLayout(false);
            tabVanChuyen.PerformLayout();
            grpThemNhanh.ResumeLayout(false);
            grpThemNhanh.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)dgvHangHoa).EndInit();
            statusStrip.ResumeLayout(false);
            statusStrip.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)errorProvider).EndInit();
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private SplitContainer splitMain;
        private TabControl tabThongTin;
        private TabPage tabKhachHang;
        private Label lblTenKH;
        private TextBox txtTenKH;
        private Label lblSDT;
        private TextBox txtSDT;
        private Label lblDiaChi;
        private TextBox txtDiaChi;
        private TabPage tabVanChuyen;
        private Label lblLoaiVC;
        private ComboBox cboLoaiVC;
        private Label lblNgayGiao;
        private DateTimePicker dtpNgayGiao;
        private Label lblGhiChu;
        private TextBox txtGhiChu;
        private GroupBox grpThemNhanh;
        private Label lblTenHang;
        private TextBox txtTenHang;
        private Label lblSoLuong;
        private TextBox txtSoLuong;
        private Label lblTrongLuong;
        private TextBox txtTrongLuong;
        private Label lblDonGia;
        private TextBox txtDonGia;
        private Button btnThemHang;
        private Button btnLuuDon;
        private Button btnDonMoi;
        private Label lblHuongDan;
        private DataGridView dgvHangHoa;
        private DataGridViewTextBoxColumn colTenHang;
        private DataGridViewTextBoxColumn colSoLuong;
        private DataGridViewTextBoxColumn colTrongLuong;
        private DataGridViewTextBoxColumn colDonGia;
        private DataGridViewTextBoxColumn colThanhTien;
        private StatusStrip statusStrip;
        private ToolStripStatusLabel lblThoiGian;
        private ToolStripStatusLabel lblSpring;
        private ToolStripStatusLabel lblTongSL;
        private ToolStripStatusLabel lblTongKL;
        private ToolStripStatusLabel lblTongTien;
        private System.Windows.Forms.Timer timerDongHo;
        private ErrorProvider errorProvider;
    }
}
